name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Create logs directory
      run: mkdir -p logs

    - name: Run tests
      run: pnpm test
      env:
        NODE_ENV: test
        TURSO_URL: ${{ secrets.TURSO_URL }}
        TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
        API_KEY: test-api-key
        ALLOWED_IPS: "127.0.0.1,::1"

    - name: Run linting
      run: pnpm lint